### ISSUE TITLE
Help on writing a realtime websocket client

### ISSUE THREAD

**Issue by geohuz** [nepeckman/nerve-rpc#5]
I don't quite understand the code as if they mixed with server and client logic together, I don't need programing a server, my requirement is very simple, open a connection to an existing remote server, send message with "subscription", and get streaming data from server in a loop. The server implemented json-rpc, so basically I would send the following information after connection:

```
{
  "jsonrpc": "2.0",
  "method": "add",
  "params": {
    "data": [
      "notify"
    ],
    "entity": "subscriptions",
    "userEmail": "xxx",
    "authToken": "KuAn",
    "project_uid": "R9bLiv4h_r0Q"
  },
  "id": 1
}
```

I would like to thank you for the help as I'm new to the nim and I'm very interested in writing something useful with it.

**Comment by vepeckman** [comment]
Hey @geohuz!

Not sure if you still need the help, but here are some pointers. I suggest using the `ws` Nim library for handling websockets. Cant easily link it at the moment, but if you search on Nim's package manager Nimble, you will find it. The documentation will explain how to send and receive data from the web socket, and you can use Nim's native JSON library to convert data to and from JSON.

Let me know if you need more info, happy to help!
